### ISSUE TITLE
number of input reads

### ISSUE THREAD

**Issue by sdwien** [giannimonaco/ABIS#1]
Dear Gianni,
I would like to know how many read you used for the analysis in the paper, or how many reads you would consider the minimum number, a good number or more than enough for the analysis?
Thanks and best,
Sophia

**Comment by giannimonaco** [comment]
Dear Sophia,

The number of reads in the fastq files is between 15-20 millions. This is a good number for gene expression quantification. Check also https://support.illumina.com/bulletins/2017/04/considerations-for-rna-seq-read-length-and-coverage-.html

Best wishes,

Gianni

**Comment by eegk** [comment]
Hi, I'm getting this error:

'x' is singular: singular fits are not implemented in 'rlm' - I'm using a tab delimitated matrix with gene symbols as rownames.

I would suggest provide a short example of the exact matrix accepted by the software.

Thank you
