### ISSUE TITLE
Input data from Affymetrix arrays

### ISSUE THREAD

**Issue by sdwien** [giannimonaco/ABIS#10]
I tried to use the ABIS tool via the web, but got an error: "An error has occurred. Check your logs or contact the app author for clarification." It works fine for the TPMPBMC.txt file, so it is not an issue of my browser, I assume.
My file contains RMA-normalized counts from human Affymetrix PrimeView arrays, has 19464 rows and 4 columns (gene symbols and 3 samples). It looks like this:

```
head test123.txt
"SCH1"	"SCH2"	"SCH3"
"1060P11.3"	3.5967598624897	3.93685508289532	3.87821946945781
"A1BG"	6.45565863125128	5.82575471633686	5.79043259640592
"A1CF"	5.34300130822687	5.68253584972171	5.30336643058087
"A2M"	4.15193049248871	4.3784780972333	3.94194736201775
"A2ML1"	3.49557726410993	3.6238503706137	3.51239887716308
"A3GALT2"	3.4001284612413	3.53329672413759	3.64071911619115
"A4GALT"	4.65199708894221	5.19605851776019	4.9648856544884
"A4GNT"	4.41943768837953	4.39662210867146	4.12529843617137
"AAAS"	5.73657599875531	5.8650512477877	5.86236578077812
```
I would be grateful for suggestions on what may be wrong here.
Thanks and best regards.
PS.: Are there some genes that "have to" be there?
PPS.: I just noticed that when selecting "RNA-Seq" as input type, it does run and output a table, but not when selecting "Microarray". Your example file works with both settings, though, and outputs different numbers of rows with each.

**Comment by giannimonaco** [comment]
Hi,

I am not entirely sure why you are getting the error message only when you
use microarray.
The data should be on linear scale. I think that RMA-normalized counts are
log2 transformed. Can you convert them back to linear scale and try again.
To convert them just apply this formula to all values: 2^value

Try this first and let me know if it works.

Gianni

**Comment by sdwien** [comment]
Hi Gianni,

thanks, I tried that. My input now looks like that:
```
"SCH1"        "SCH2"        "SCH3"
"1060P11.3"     12.0985300026222        15.314804898821 14.7048429344018
"A1BG"  87.7701599438797        56.7187847325014        55.346976271497
"A1CF"  40.5885615838657        51.3586668803532        39.4886578972973
"A2M"   17.7768831665421        20.7995166455123        15.3689570632719
"A2ML1" 11.279078224529 12.3278590812149        11.4113603223342
"A3GALT2"       10.5570032667953        11.5778601011023        12.4728488587772
"A4GALT"        25.1414698030673        36.6580596081672        31.2305409681272
"A4GNT" 21.3984988711742        21.0627529726873        17.4517334181841
"AAAS"  53.3189327732681        58.2849397258712        58.1765476599487
```
It still works when I set the input to RNA-Seq (results file attached, looks weird with numbers over 100 in some rows), but not with Microarray set where I am getting the same error as before. 
[test123lin.txt_deconvolution.txt](https://github.com/giannimonaco/ABIS/files/4310610/test123lin.txt_deconvolution.txt)
I can get the raw intensities for these arrays. How did you do it with the Illumina arrays you used?
Thanks for your help. I would really like to implement this tool for our facility.
Best, Sophia

**Comment by giannimonaco** [comment]
Hi Sophia,

yes, the results look weird because your data is microarray and it is not
compatible with the RNA-Seq normalisation.
The microarray data need to be in the linear scale and then ABIS will
perform a quintile normalisation. Then you should obtain good results,
although consider that you could still have some technical and biological
variability.

Best,
Gianni
