### ISSUE TITLE
Column names in Gene Browser

### ISSUE THREAD

**Issue by sdwien** [giannimonaco/ABIS#2]
Just a small issue: In the Gene Browser, when downloading the data in tabular format, the column names for sample and expression are switched I believe:
gene_name	cell_type	expression	sample
EGFR	B_Ex	RHH5218	-9.1371
EGFR	B_Ex	RHH5247	-9.1371
EGFR	B_Ex	RHH5276	-9.1371
EGFR	B_Ex	RHH5310	-9.1371
EGFR	B_naive	RHH5216	-9.1371
EGFR	B_naive	RHH5245	-9.1371

Best,
Sophia

**Comment by giannimonaco** [comment]
Thank you for pointing it out. The column names are now correct.

Best,
Gianni
