### ISSUE TITLE
could the deconvolution results be compared across samples and cell types?

### ISSUE THREAD

**Issue by HelloYiHan** [giannimonaco/ABIS#4]
Hi Gianni,

Thank you for your excellent work. I am very interested in ABIS.

I was wondering if the results of ABIS represent the absolute proportion of cell types and could be compared across samples and across cell types or not.

The reason of my question is that some other similar methods, like MCP-counter(DOI 10.1186/s13059-016-1070-5) and xCell(DOI 10.1186/s13059-017-1349-1), only generate cell type enrichment scores and these scores don't represent the percentage of the corresponding cell types.

Thanks again
Yi Han

**Comment by giannimonaco** [comment]
Dear Yi Han,

Thank you for your interest on ABIS! 
Yes, ABIS should give you the absolute proportions of gene expression data of Peripheral Blood Mononuclear Cell (PBMCs). 
However, I would still be careful with the results as I believe that deconvolution still suffer a lot from biological variability.

Best,

Gianni
