### ISSUE TITLE
information about the output file

### ISSUE THREAD

**Issue by ConcettaDe4** [giannimonaco/ABIS#7]
Dear Gianni,

I am interested in using your program to perform deconvolution of bulk RNA-seq data. 

I have two questions about the output that I can obtain from the software: 
1.	Will I identify the cell types that contributed (most) to the bulk data and the abundance of the different cell types that made up the PBMCs from which the bulk data are derived?
2.	Will I obtain transformed bulk RNAseq data, for example, can I obtain different expression tables (gene vs expression level) for each cell type that constitutes my bulk RNA-seq data?

Thank you.

Concetta

**Comment by giannimonaco** [comment]
Dear Concetta,

Thank you for your interest!
You will obtain the first point, meaning the frequency of each immune cell type in your bulk sample.

Gianni
