### ISSUE TITLE
Running the algortihm locally

### ISSUE THREAD

**Issue by drhmoosavi** [giannimonaco/ABIS#9]
Hi,
I would like to run my microarrays gene expressions through the algorithm on my PC. I have savedthe repository but couldn't understand what to run in either the ui.R or the server.R files. I can see in server.R there are variables `sigMicroarray , target , MedianTPM and Annotation` that need the file location on the disk, which I changed to the correct path. What next? how to generate output file and where will it be saved ?

Thanks

**Comment by giannimonaco** [comment]
Hi,

to run the shiny app locally, you should open either the ui.R or the server.R file in R studio. RStudio will recognize the Shiny script and provide a Run App button (at the top of the editor). Either click this button to launch your app or use the keyboard shortcut: Command+Shift+Enter (Control+Shift+Enter on Windows).

Check also: https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/

Best,
Gianni

**Comment by drhmoosavi** [comment]
Thanks for the response. I did find out how to run the codes, however, I can't get over an warning R gives me after I upload my gene expression data using shiny interface. I am not sure where the results are correct.
The warning is `Warning in rlm.default(as.matrix(sigMicroarray[genes, ]), x) :
  'rlm' failed to converge in 20 steps`
any idea?
Thanks again.

**Comment by giannimonaco** [comment]
Hello,

can you try the last version of ABIS? It should not give you the warning in
the last version.

Let me know,
Gianni

**Comment by drhmoosavi** [comment]
It worked! however, when I download the result, cell population names (in the row names) is missing in the txt file.

**Comment by giannimonaco** [comment]
Sorry, you are right. I fixed that too now!

**Comment by sam-israel** [comment]
I have cloned the repo ( ```git clone https://github.com/giannimonaco/ABIS```) and ran the Shiny app locally (with the default RNA seq signature matrix - on **400** samples). 

I get a similar message to the user above 

```
Warning in rlm.default(as.matrix(sigRNAseq[genes, ]), x, maxit = 100) :
  'rlm' failed to converge in 100 steps
```

Is it important? Does it invalidate the deconvolution results? How can this be fixed?

**Comment by giannimonaco** [comment]
Hi,
the results should still be good even if you get the warning.
You could increase the value given to the maxit argument to avoid the
warning.
